*&---------------------------------------------------------------------*
*& Report YTEST03
*&---------------------------------------------------------------------*
*&
*&---------------------------------------------------------------------*
REPORT YTEST03 NO STANDARD PAGE HEADING.

INCLUDE <LINE>.
INCLUDE <ICON>.

DATA: L_COLOR TYPE CHAR25 VALUE '색깔 테스트'.

FORMAT COLOR COL_HEADING ON.
WRITE: / L_COLOR.
FORMAT COLOR OFF.

FORMAT INVERSE ON.
WRITE: / L_COLOR.
FORMAT COLOR OFF.

FORMAT COLOR 7.
WRITE: / L_COLOR.
FORMAT COLOR 4.

ULINE /1(50).
WRITE: / SY-VLINE NO-GAP,LINE_TOP_LEFT_CORNER AS LINE.
ULINE 3(48).
WRITE: / SY-VLINE NO-GAP,SY-VLINE NO-GAP.

DATA: INFO(20) VALUE 'INFORMATION'.
WRITE: / SY-UNAME QUICKINFO 'USER NAME'.
WRITE: / ICON_INFORMATION AS ICON QUICKINFO info
HOTSPOT COLOR COL_POSITIVE.

ULINE.
DATA SALES TYPE P VALUE 146260.
WRITE SALES CURRENCY 'USD' ROUND 3 DECIMALS 1.
WRITE SALES CURRENCY 'KRW' ROUND 3 DECIMALS 1.
WRITE SALES CURRENCY 'USD' ROUND 2 DECIMALS 2.
WRITE SALES CURRENCY 'KRW' ROUND 2 DECIMALS 2.
